openapi: 3.0.3
info:
  description: Testing app for bakalarsky project
  version: 1.0.1
  title: Openshift node pod
paths:
  /:
    get:
      description: Greeting from server
      responses:
        '200':
          description: Greeting message.
  '/reddit/:subreddit':
    get:
      description: Call specific subreddit and return data from it
      responses:
        '200':
          description: Data from subreddit.

